//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WjbuGangVer2_WebNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.MatHangs = new HashSet<MatHang>();
        }
    
        public int MaHD { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }

        internal void Add(MatHang pro)
        {
            throw new NotImplementedException();
        }

        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> TongTien { get; set; }
        public int MaPT { get; set; }
        public int AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual PhuongThucThanhToan PhuongThucThanhToan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatHang> MatHangs { get; set; }
    }
    public class GiohangItem
    {
        public MatHang _shopping_product { get; set; }
        public int _shopping_quantity { get; set; }
    }
    //Gio hang
    public class Giohang
    {
        List<GiohangItem> items =new List<GiohangItem>();
        public IEnumerable<GiohangItem> Items
        {
            get { return items; }
        }
        public void Add(MatHang _pro, int _quantity = 1)
        {
            var item = items.FirstOrDefault(s => s._shopping_product.MaMH == _pro.MaMH);
            if (item == null)
            {
                items.Add(new GiohangItem
                {
                    _shopping_product = _pro,
                    _shopping_quantity = _quantity
                });
            }
            else
            {
                item._shopping_quantity += _quantity;
            }   
        }
    }
}
