//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WjbuGangVer2_WebNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatHang()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int MaMH { get; set; }
        public int MaLoai { get; set; }
        public int DonGia { get; set; }
        public string TenMH { get; set; }
        public string MoTa { get; set; }
        public string Hang { get; set; }
        public string HinhChinh { get; set; }
        public string Hinh1 { get; set; }
        public string Hinh2 { get; set; }
        public string Hinh3 { get; set; }
        public string Hinh4 { get; set; }
        public string BaoHanh { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string HDD { get; set; }
        public string VGA { get; set; }
        public string Monitor { get; set; }
        public string Port { get; set; }
        public string Audio { get; set; }
        public string NumberPad { get; set; }
        public string HDH { get; set; }
        public string Pin { get; set; }
        public string Weight { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual LoaiMH LoaiMH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
